name: Env Selector CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      with:
        node-version: ${{ matrix.node-version }}
    - name: install and build
      run: |
        npm install
        npm run compile
      env:
        CI: true
