name: 'Release Extension'

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install and Build
      run: |
        npm install
        npm run compile
    - name: Release Extension
      uses: JCofman/vscodeaction@master
      env:
        PUBLISHER_TOKEN: ${{ secrets.VSC_PUBLISH_TOKEN }}
      with:
        args: publish -p $PUBLISHER_TOKEN
